/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import CONTROL.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author ANIBAL
 */
public class Habitacion1 extends javax.swing.JPanel {

  
    public Habitacion1() {
        initComponents();
    }
    
        Conexion enlazar = new Conexion ();
        Connection conexion = (Connection) enlazar.conectar();
        
        
    public void mostrar1(){
        
      
        
        String sql= "Select * from huesped";
        Statement st;
        
        
        System.out.println(sql);
        DefaultTableModel model =new DefaultTableModel();
        
        model.addColumn("nombre");
        model.addColumn("apellido");
        model.addColumn("dni");
        model.addColumn("edad");
        
        TABLA.setModel(model);
        
        String [] datos = new String[4];
        try{
            st= (Statement) conexion.createStatement();
            ResultSet rs= (ResultSet) st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                model.addRow(datos);
                
            }
            }catch (SQLException e){
                    JOptionPane.showMessageDialog(null,"error"+e.toString());
                    }
            
        }
        public void mostrar2(){
        
      
        
        String sql= "Select * from empleado";
        Statement st;
        
        
        System.out.println(sql);
        DefaultTableModel model =new DefaultTableModel();
        
        model.addColumn("codigo");
        model.addColumn("nombre");
        model.addColumn("apellido");
        model.addColumn("cargo");
        model.addColumn("turno");
        model.addColumn("dni_huesped");
        
        TABLA.setModel(model);
        
        String [] datos = new String[6];
        try{
            st= (Statement) conexion.createStatement();
            ResultSet rs= (ResultSet) st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                
                model.addRow(datos);
                
            }
            }catch (SQLException e){
                    JOptionPane.showMessageDialog(null,"error"+e.toString());
                    }
            
        }
     
        public void mostrar3(){
        
      
        
        String sql= "Select * from factura";
        Statement st;
        
        
        System.out.println(sql);
        DefaultTableModel model =new DefaultTableModel();
        
        model.addColumn("numero_dias");
        model.addColumn("tipo_habitacion ");
        model.addColumn("precio");
        model.addColumn("fecha_entrada");
        model.addColumn("fecha_salida");
        model.addColumn("total");
        
        TABLA.setModel(model);
        
        String [] datos = new String[6];
        try{
            st= (Statement) conexion.createStatement();
            ResultSet rs= (ResultSet) st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                
                model.addRow(datos);
                
            }
            }catch (SQLException e){
                    JOptionPane.showMessageDialog(null,"error"+e.toString());
                    }
            
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btncliente = new javax.swing.JButton();
        btnfactura = new javax.swing.JButton();
        btnempleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(1052, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-cama-matrimonial-96.png"))); // NOI18N
        jLabel2.setText("REPORTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-cliente-96.png"))); // NOI18N
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        btnfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-factura-96.png"))); // NOI18N
        btnfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaActionPerformed(evt);
            }
        });

        btnempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-trabajo-permanente-96.png"))); // NOI18N
        btnempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempleadoActionPerformed(evt);
            }
        });

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TABLA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btncliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnempleado)
                        .addGap(71, 71, 71)
                        .addComponent(btnfactura))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnfactura)
                    .addComponent(btncliente)
                    .addComponent(btnempleado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        mostrar1();
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempleadoActionPerformed
        mostrar2();
    }//GEN-LAST:event_btnempleadoActionPerformed

    private void btnfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaActionPerformed
        mostrar3();
    }//GEN-LAST:event_btnfacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TABLA;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnempleado;
    private javax.swing.JButton btnfactura;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
