
package VISTA;

import java.sql.Connection;
import CONTROL.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    Conexion  enlace  = new Conexion();
    Connection conect = enlace.conectar();
    
    Color DefaulColor,ClickedColor;
    
    public Principal() {
        
        initComponents();
        InitContent();
        setDate();
        probar_conexion();
        
        DefaulColor = new Color(102,255,102);
        ClickedColor = new Color(0,105,213);
        
       btnEmpleado.setBackground(DefaulColor);
       btnHuesped.setBackground(DefaulColor);
       btnNosotros.setBackground(DefaulColor);
       btnFactura.setBackground(DefaulColor);
       btnHabitacion.setBackground(DefaulColor);
        
       
    }
    private void InitContent(){
        Nosotros1 nos1 = new Nosotros1();
        nos1.setSize(776,402);
        nos1.setLocation(0,0);
        
        content.removeAll();
        content.add(nos1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }
    
    private void setDate()
    {
    LocalDate now= LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String[] meses={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Setiembre","Octubre","Noviembre","Diciembre"};
    dateText.setText("Hoy es "+dia+" de "+meses[month-1]+" de "+year);
    }
    
    public void probar_conexion(){
        if(conect == null){
            JOptionPane.showMessageDialog(null, "No se logro la conexion a la base de datos");            
        }else{
            JOptionPane.showMessageDialog(null, "Conexion establecida a la base de datos");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEmpleado = new javax.swing.JButton();
        btnHabitacion = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnHuesped = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Eslogan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(102, 255, 102));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icono.PNG"))); // NOI18N
        jLabel3.setText("iBed");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("===");

        btnEmpleado.setBackground(new java.awt.Color(102, 255, 102));
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-trabajo-permanente-48.png"))); // NOI18N
        btnEmpleado.setText("EMPLEADO");
        btnEmpleado.setBorder(null);
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadoMousePressed(evt);
            }
        });
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnHabitacion.setBackground(new java.awt.Color(102, 255, 102));
        btnHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-cama-matrimonial-48.png"))); // NOI18N
        btnHabitacion.setText("REPORTES");
        btnHabitacion.setBorder(null);
        btnHabitacion.setBorderPainted(false);
        btnHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHabitacionMousePressed(evt);
            }
        });
        btnHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionActionPerformed(evt);
            }
        });

        btnFactura.setBackground(new java.awt.Color(102, 255, 102));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-factura-48.png"))); // NOI18N
        btnFactura.setText("FACTURA");
        btnFactura.setBorder(null);
        btnFactura.setBorderPainted(false);
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFacturaMousePressed(evt);
            }
        });
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnHuesped.setBackground(new java.awt.Color(102, 255, 102));
        btnHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-cliente-48.png"))); // NOI18N
        btnHuesped.setText("HUESPED");
        btnHuesped.setBorder(null);
        btnHuesped.setBorderPainted(false);
        btnHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuesped.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHuespedMousePressed(evt);
            }
        });
        btnHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuespedActionPerformed(evt);
            }
        });

        btnEXIT.setText("SALIR");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });

        btnNosotros.setBackground(new java.awt.Color(102, 255, 102));
        btnNosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-hotel-48.png"))); // NOI18N
        btnNosotros.setText("NOSOTROS");
        btnNosotros.setBorder(null);
        btnNosotros.setBorderPainted(false);
        btnNosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNosotros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNosotrosMousePressed(evt);
            }
        });
        btnNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNosotrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNosotros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnEXIT))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFactura)
                .addGap(14, 14, 14)
                .addComponent(btnEXIT)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(153, 255, 153));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Registro de cliente/ Registro de empleado / Consulta de habitaciones/ Cobros");

        dateText.setFont(new java.awt.Font("SimSun", 3, 24)); // NOI18N
        dateText.setText("Hoy es {dayname} {day} del {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Eslogan.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        Eslogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/emoji1.PNG"))); // NOI18N
        Eslogan.setText("¡VAMOS A DORMIR!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(Eslogan, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        Empleado1 Emp1 = new Empleado1();
        Emp1.setSize(776,402);
        Emp1.setLocation(0,0);
        
        content.removeAll();
        content.add(Emp1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionActionPerformed
        Habitacion1 hab1 = new Habitacion1();
        hab1.setSize(776,402);
        hab1.setLocation(0,0);
        
        content.removeAll();
        content.add(hab1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnHabitacionActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        Factura1 Fac1 = new Factura1();
        Fac1.setSize(812, 548);
        Fac1.setLocation(0,0);
        
        content.removeAll();
        content.add(Fac1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuespedActionPerformed
        Huesped1 Hue1 = new Huesped1();
        Hue1.setSize(776,402);
        Hue1.setLocation(0,0);
        
        content.removeAll();
        content.add(Hue1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnHuespedActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNosotrosActionPerformed
        Nosotros1 nos1 = new Nosotros1();
        nos1.setSize(776,402);
        nos1.setLocation(0,0);
        
        content.removeAll();
        content.add(nos1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnNosotrosActionPerformed

    private void btnNosotrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNosotrosMousePressed
       btnNosotros.setBackground(ClickedColor);
       btnEmpleado.setBackground(DefaulColor);
       btnHuesped.setBackground(DefaulColor);
       btnFactura.setBackground(DefaulColor);
       btnHabitacion.setBackground(DefaulColor);
    }//GEN-LAST:event_btnNosotrosMousePressed

    private void btnHuespedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuespedMousePressed
       btnNosotros.setBackground(DefaulColor);
       btnHuesped.setBackground(ClickedColor);
       btnEmpleado.setBackground(DefaulColor);
       btnFactura.setBackground(DefaulColor);
       btnHabitacion.setBackground(DefaulColor);
    }//GEN-LAST:event_btnHuespedMousePressed

    private void btnEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMousePressed
       btnNosotros.setBackground(DefaulColor);
       btnHuesped.setBackground(DefaulColor);
       btnEmpleado.setBackground(ClickedColor);
       btnFactura.setBackground(DefaulColor);
       btnHabitacion.setBackground(DefaulColor);
    }//GEN-LAST:event_btnEmpleadoMousePressed

    private void btnHabitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabitacionMousePressed
       btnNosotros.setBackground(DefaulColor);
       btnHuesped.setBackground(DefaulColor);
       btnEmpleado.setBackground(DefaulColor);
       btnHabitacion.setBackground(ClickedColor);
       btnFactura.setBackground(DefaulColor);
      
    }//GEN-LAST:event_btnHabitacionMousePressed

    private void btnFacturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMousePressed
       btnNosotros.setBackground(DefaulColor);
       btnHuesped.setBackground(DefaulColor);
       btnEmpleado.setBackground(DefaulColor);
       btnHabitacion.setBackground(DefaulColor);
       btnFactura.setBackground(ClickedColor);
    }//GEN-LAST:event_btnFacturaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eslogan;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnHabitacion;
    private javax.swing.JButton btnHuesped;
    private javax.swing.JButton btnNosotros;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
